//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Crm.Infrastructure
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerToTag
    {
        public int CustomerId { get; set; }
        public int TagId { get; set; }
        public System.DateTime Created { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual Tag Tag { get; set; }
    }
}
